trigger:
  branches:
    include:
    - refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Terraform'
    inputs:
      TargetFolder: $(build.artifactstagingdirectory)/Terraform
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...
